#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Creuna.MonoDroid.PageHelper.Resource", IsApplication=false)]

namespace Creuna.MonoDroid.PageHelper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int activeDot = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int dotCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int dotDrawable = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int dotSpacing = 2130771972;
			
			// aapt resource value: 0x7f010006
			public static int dotType = 2130771974;
			
			// aapt resource value: 0x7f010000
			public static int gdPageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010005
			public static int gravity = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int gd_page_indicator_dot = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int gd_page_indicator_dot_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int gd_page_indicator_dot_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int gd_page_indicator_dot_normal_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int gd_page_indicator_dot_normal_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int gd_page_indicator_dot_normal_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int gd_page_indicator_dot_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int gd_page_indicator_dot_selected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int gd_page_indicator_dot_selected_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int gd_page_indicator_dot_selected_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int gd_page_indicator_dot_selected_pressed = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030001
			public static int bottom = 2130903041;
			
			// aapt resource value: 0x7f030006
			public static int center = 2130903046;
			
			// aapt resource value: 0x7f030005
			public static int center_horizontal = 2130903045;
			
			// aapt resource value: 0x7f030004
			public static int center_vertical = 2130903044;
			
			// aapt resource value: 0x7f030002
			public static int left = 2130903042;
			
			// aapt resource value: 0x7f030008
			public static int multiple = 2130903048;
			
			// aapt resource value: 0x7f030003
			public static int right = 2130903043;
			
			// aapt resource value: 0x7f030007
			public static int single = 2130903047;
			
			// aapt resource value: 0x7f030000
			public static int top = 2130903040;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public static int GreenDroid = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int GreenDroid_Widget = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int GreenDroid_Widget_PageIndicator = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int Theme_GreenDroid = 2130968579;
			
			// aapt resource value: 0x7f040005
			public static int Theme_GreenDroid_Light = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int Theme_GreenDroid_Light_NoTitleBar = 2130968582;
			
			// aapt resource value: 0x7f040004
			public static int Theme_GreenDroid_NoTitleBar = 2130968580;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PageIndicator = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 1
			public static int PageIndicator_activeDot = 1;
			
			// aapt resource value: 0
			public static int PageIndicator_dotCount = 0;
			
			// aapt resource value: 2
			public static int PageIndicator_dotDrawable = 2;
			
			// aapt resource value: 3
			public static int PageIndicator_dotSpacing = 3;
			
			// aapt resource value: 5
			public static int PageIndicator_dotType = 5;
			
			// aapt resource value: 4
			public static int PageIndicator_gravity = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
